import Head from 'next/head'
// import styles from '../../../styles/home.module.css'
import HomePage from '../src/components/home/home-page';

export default function Home(props) {
  const {data}= props
  return (
    <div >
      <Head>
        <title>Events App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HomePage data = {data} />

    </div>
  )
}

// This code is executed first and only runs on the server side never on the client side
export async function getServerSideProps() {
  const data= await import ('/data/data.json') 
  const {events_categories}=data
  // console.log(events_categories);
// In case we import the data from an API

// we should have this code: import homePage from './../components/home/home-page';
//   const res = await fetch('URL')
//   const data = await res.json()
// Here we can put any sensitive information since the browser never sees it 
// like keys, etc
  return {
    props: {
      data: events_categories,
    },
  };
}